CREATE TABLE Students (
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	FirstName NVARCHAR(25) NOT NULL,
	LastName NVARCHAR(25) NOT NULL,
	Age INT NOT NULL,
);

CREATE TABLE Teachers (
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	FirstName NVARCHAR(25) NOT NULL,
	LastName NVARCHAR(25) NOT NULL,
	Age INT NOT NULL,
	SubjectId INT FOREIGN KEY REFERENCES Subjects(Id),
);

CREATE TABLE Subjects (
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(40) NOT NULL,
);

